[package]
name = "bot_any_env_cf_worker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bot_any_cal = { path = "../bot_any_cal" }
worker = "*"
