[workspace]
members = [
    "crates/app",
    "crates/crowdin_client",
    "crates/mcapi",
    "crates/kal-serenity",
    "crates/engine",
    "crates/prisma",
    "crates/update-java-asset",
    "crates/query",
]