env_files = [
    { path = "./.env.development", profile = "development" },
    { path = "./.env.production", profile = "production" },
    { path = "./.env" }
]

[config]
default_to_workspace = false

[tasks.prisma]
command = "cargo"
cwd = "crates/engine"
args = ["run", "-p", "prisma", "--", "${@}"]

[tasks.query]
command = "cargo"
args = ["run", "-p", "query"]

[tasks.update-java-asset]
command = "cargo"
args = ["run", "-p", "update-java-asset"]

[tasks.update-bedrock-asset]
command = "cargo"
args = ["run", "-p", "update-bedrock-asset"]

[tasks.update-dungeons-asset]
command = "cargo"
args = ["run", "-p", "update-dungeons-asset"]

[tasks.app]
command = "cargo"
args = ["run", "-p", "app"]
