name: Fly Deploy Main

on:
  push:
    branches: [main]
    paths:
      - Cargo.lock
      - fly.toml
      - Makefile.toml
      - crates/app/**
      - crates/crowdin_client/**
      - crates/engine/**
      - crates/kal-serenity/**
      - crates/mcapi/**
      - Dockerfile
      - .github/workflows/fly-deploy-main.yml

concurrency:
  group: "fly-deploy-main"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: v0.1.110
      - run: "flyctl deploy --remote-only --app crowdin-strife"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
