name: 'List up "Intend to Ship" PR'

on:
  pull_request:
    branches: ['main']
    types:
      - opened
      - synchronize
  workflow_dispatch:

concurrency:
  group: 'list-up-intend-to-ship'
  cancel-in-progress: false

jobs:
  make_pr:
    name: 'List-up PR'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'PR existence check'
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pr_id=$(gh pr list \
            --repo "$GITHUB_REPOSITORY" \
            --base main \
            --head beta \
            --state open \
            --json number \
            --jq '.[0].number' \
          )
          if ((pr_id)); then
            echo "exist=true" >> "$GITHUB_OUTPUT"
            echo "pr=$pr_id" >> "$GITHUB_OUTPUT"
          fi
      - name: 'Edit PR'
        if: 'steps.check.outputs.exist'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr edit "${{ steps.check.outputs.pr }}" \
            --body "$(\
              gh pr list \
                --state closed \
                --base beta \
                --label "living on beta" \
                --json number \
                --jq '.[].number | tostring | "- #" + .' \
            )"
