name: 'Make "Intend to Ship" PR'

on:
  pull_request:
    branches: ['beta']
    types:
      - closed
  workflow_dispatch:

concurrency:
  group: 'make-intend-to-ship'
  cancel-in-progress: false

jobs:
  make_pr:
    name: 'Make PR'
    runs-on: ubuntu-latest
    steps:
      - name: 'PR existence check'
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_count=$(gh pr list \
            --repo "$GITHUB_REPOSITORY" \
            --base main \
            --head beta \
            --state open \
            --json title \
            --jq length \
          )
          if ((pr_count > 0)); then
            echo "skip = true" >> "$GITHUB_OUTPUT"
          fi
      - name: 'Create PR'
        if: '!steps.check.outputs.skip'
        run: |
          url=$(gh pr create \
            --base main \
            --head beta \
            --title "Intend to Ship" \
            --label "Type: Intend to Ship" \
            --no-maintainer-edit \
          )
          gh issue pin "$url"
